[package]
name = "desfn"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.126" }
erased-serde = "0.3.16"

[dev-dependencies]
serde = { version = "1.0.126", features = ["derive"] }
once_cell = "1.8.0"
serde_json = "1.0.64"
