[package]
name = "desfn"
version = "0.1.0"
edition = "2018"

[dependencies]
erased-serde = "0.3.16"
serde = "1.0.126"
serde-value = "0.7.0"

[dev-dependencies]
serde = { version = "1.0.126", features = ["derive"] }
once_cell = "1.8.0"
serde_json = "1.0.64"
