[package]
name = "desfn"
version = "0.1.0"
edition = "2018"

[dependencies]
erased-serde = "0.3.0"
serde = "1.0.0"
serde-value = "0.7.0"

[dev-dependencies]
serde = { version = "1.0.0", features = ["derive"] }
once_cell = "1.0.0"
serde_json = "1.0.0"
